controller_manager:
  ros__parameters:
    update_rate: 100

    diff_drive_base_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


diff_drive_base_controller:
  ros__parameters:
    publish_rate: 50.0

    base_frame_id: Chassis
    odom_frame_id: odom
    enable_odom_tf: true

    left_wheel_names:
      - WFL-Rev
      - WML-Rev
      - WRL-Rev

    right_wheel_names:
      - WFR-Rev
      - WMR-Rev
      - WRR-Rev

    wheel_radius: 0.095
    wheel_separation: 0.435

    cmd_vel_topic: /cmd_vel
    cmd_vel_timeout: 0.25
    use_stamped_vel: false

    linear:
      x:
        has_velocity_limits: true
        max_velocity: 1.0
        has_acceleration_limits: true
        max_acceleration: 1.0

    angular:
      z:
        has_velocity_limits: true
        max_velocity: 2.0
        has_acceleration_limits: true
        max_acceleration: 2.0
