ekf_local_node:
  ros__parameters:
    frequency: 30.0

    publish_tf: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    two_d_mode: true

    odom0: Front_Zed/zed_node/odom
    odom0_config: [true, true, true,
                   false, false, false,
                   true, true, true,
                   false, false, true,
                   false, false, false]

    imu0: Front_Zed/zed_node/imu/data
    imu0_config: [false, false, false,
                  true, true, true,
                  false, false, false,
                  true, true, true,
                  true, true, true]

navsat_transform_node:
  ros__parameters:
    frequency: 30.0

    wait_for_datum: false # change this and datum information
    use_odometry_yaw: true

    magnetic_declination_radians: 0.0
    yaw_offset: 0.0
    zero_altitude: true

ekf_global_node:
  ros__parameters:
    frequency: 30.0

    publish_tf: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: map

    two_d_mode: true

    odom0: /odometry/filtered
    odom0_config: [true, true, true,
                   true, true, true,
                   true, true, true,
                   false, false, false,
                   false, false, false]

    odom1: /odometry/gps
    odom1_config: [true, true, true,
                   false, false, false,
                   false, false, false,
                   false, false, false,
                   false, false, false]