# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - rover_arm_controller
    - rover_gripper_controller

  rover_arm_controller:
    type: FollowJointTrajectory
    joints:
      - Arm_Base_Rotate
      - Arm_Shoulder
      - Arm_Elbow_Tilt
      - Arm_Elbow_Rotate
      - Arm_Wrist_Tilt
  rover_gripper_controller:
    type: FollowJointTrajectory
    joints:
      - Arm_Wrist_Rotate