waypoints:
  start_zone:
    latitude: 38.4063
    longitude: -110.7918
    
  science_1:
    latitude: 38.4070
    longitude: -110.7920
    
  science_2:
    latitude: 38.4075
    longitude: -110.7925
    
  return_point:
    latitude: 38.4063
    longitude: -110.7918
    
